package asg2;

/**
 * @author    : Enrico Junior
 * Student ID : E2100297 
 * HELPAidGUI.java
 * Date : 24-12-2023
 * This part is completed
 * This code was compiled using Apache NetBeans IDE Version 20
 * Assignment 2 BIT203
 * Current JDK Version (javac version): 19
 * Java(TM) SE Runtime Environment (build 19+36-2238) 
 * 
 */

// LIST OF THE UTILTIES REQUIRED FOR THE GUI
import javax.swing.JOptionPane; 

/**
 * The HELPAidGUI is a driver program that controls the system of the HELP Aid Management
 * This is where the program starts 
 * In here, there will be ActionListener event for each button, directing Users to the specified Panel
 */
public class HELPAidGUI extends javax.swing.JFrame {
    // LIST OF THE DECLARED STATIC VARIABLES
    // Declare single working HELPAid Object for the HELPAid class
    private static HELPAid HELPAid = new HELPAid();

    /**
     * HELPAidGUI Form
     * Default constructor of HELPAidGUI to initialize all of the required components
     */
    public HELPAidGUI() {
        // Call the initComponents() method that is used to 
        // initialize all of the required components for the GUI builder
        initComponents();       
    }
    
    // Init @SuppressWarnings generated by Apache NetBeans
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        MainGUIPanelFrame = new javax.swing.JPanel();
        SideLeftPanel = new javax.swing.JPanel();
        ExitButtonGUI = new javax.swing.JButton();
        HELPAidLabel = new javax.swing.JLabel();
        HELPAidLogo = new javax.swing.JLabel();
        HELPAidSystemLabel = new javax.swing.JLabel();
        DisplayUsersBtn = new javax.swing.JButton();
        HELPAdminLoginBtn = new javax.swing.JButton();
        HELPOrgRepLoginBtn = new javax.swing.JButton();
        EnterApplicantBtn = new javax.swing.JButton();
        HELPDonorLoginBtn = new javax.swing.JButton();
        HELPLOGOLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        setSize(new java.awt.Dimension(700, 500));

        MainGUIPanelFrame.setBackground(new java.awt.Color(255, 255, 255));
        MainGUIPanelFrame.setPreferredSize(new java.awt.Dimension(700, 500));

        SideLeftPanel.setBackground(new java.awt.Color(0, 133, 255));
        SideLeftPanel.setPreferredSize(new java.awt.Dimension(300, 500));

        ExitButtonGUI.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        ExitButtonGUI.setText("Exit");
        ExitButtonGUI.setPreferredSize(new java.awt.Dimension(80, 30));
        ExitButtonGUI.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ExitButtonGUIActionPerformed(evt);
            }
        });

        HELPAidLabel.setFont(new java.awt.Font("Arial", 1, 40)); // NOI18N
        HELPAidLabel.setForeground(new java.awt.Color(255, 255, 255));
        HELPAidLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        HELPAidLabel.setText("HELPAid");

        HELPAidLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/asg2/bwink-med-12-single-06.jpg"))); // NOI18N
        HELPAidLogo.setText("jLabel1");

        javax.swing.GroupLayout SideLeftPanelLayout = new javax.swing.GroupLayout(SideLeftPanel);
        SideLeftPanel.setLayout(SideLeftPanelLayout);
        SideLeftPanelLayout.setHorizontalGroup(
            SideLeftPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SideLeftPanelLayout.createSequentialGroup()
                .addGroup(SideLeftPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(SideLeftPanelLayout.createSequentialGroup()
                        .addGap(48, 48, 48)
                        .addComponent(HELPAidLogo, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 46, Short.MAX_VALUE))
                    .addComponent(HELPAidLabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
            .addGroup(SideLeftPanelLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(ExitButtonGUI, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        SideLeftPanelLayout.setVerticalGroup(
            SideLeftPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, SideLeftPanelLayout.createSequentialGroup()
                .addGap(70, 70, 70)
                .addComponent(HELPAidLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(HELPAidLogo, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(ExitButtonGUI, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18))
        );

        HELPAidSystemLabel.setFont(new java.awt.Font("Arial", 1, 32)); // NOI18N
        HELPAidSystemLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        HELPAidSystemLabel.setText("HELPAid SYSTEM");

        DisplayUsersBtn.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        DisplayUsersBtn.setText("Display All Users");
        DisplayUsersBtn.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        DisplayUsersBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DisplayUsersBtnActionPerformed(evt);
            }
        });

        HELPAdminLoginBtn.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        HELPAdminLoginBtn.setText("Login as HELP Aid Admin");
        HELPAdminLoginBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HELPAdminLoginBtnActionPerformed(evt);
            }
        });

        HELPOrgRepLoginBtn.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        HELPOrgRepLoginBtn.setText("Login as Representative");
        HELPOrgRepLoginBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HELPOrgRepLoginBtnActionPerformed(evt);
            }
        });

        EnterApplicantBtn.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        EnterApplicantBtn.setText("Enter as Applicant");
        EnterApplicantBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EnterApplicantBtnActionPerformed(evt);
            }
        });

        HELPDonorLoginBtn.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        HELPDonorLoginBtn.setText("Login as Donor");
        HELPDonorLoginBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HELPDonorLoginBtnActionPerformed(evt);
            }
        });

        HELPLOGOLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/asg2/helplogo.png"))); // NOI18N
        HELPLOGOLabel.setPreferredSize(new java.awt.Dimension(150, 67));

        javax.swing.GroupLayout MainGUIPanelFrameLayout = new javax.swing.GroupLayout(MainGUIPanelFrame);
        MainGUIPanelFrame.setLayout(MainGUIPanelFrameLayout);
        MainGUIPanelFrameLayout.setHorizontalGroup(
            MainGUIPanelFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MainGUIPanelFrameLayout.createSequentialGroup()
                .addComponent(SideLeftPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(MainGUIPanelFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(MainGUIPanelFrameLayout.createSequentialGroup()
                        .addGroup(MainGUIPanelFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(MainGUIPanelFrameLayout.createSequentialGroup()
                                .addGap(46, 46, 46)
                                .addComponent(HELPAidSystemLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 295, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(MainGUIPanelFrameLayout.createSequentialGroup()
                                .addGap(57, 57, 57)
                                .addGroup(MainGUIPanelFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(HELPAdminLoginBtn, javax.swing.GroupLayout.DEFAULT_SIZE, 273, Short.MAX_VALUE)
                                    .addComponent(HELPOrgRepLoginBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(EnterApplicantBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(HELPDonorLoginBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(DisplayUsersBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                        .addContainerGap(59, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, MainGUIPanelFrameLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(HELPLOGOLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
        );
        MainGUIPanelFrameLayout.setVerticalGroup(
            MainGUIPanelFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(SideLeftPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(MainGUIPanelFrameLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(HELPLOGOLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 68, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(HELPAidSystemLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(DisplayUsersBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(HELPAdminLoginBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(HELPOrgRepLoginBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(EnterApplicantBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(HELPDonorLoginBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(83, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(MainGUIPanelFrame, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(MainGUIPanelFrame, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
    
    /**
     * The method below is used to add an event to exit the GUI Program 
     * Method: ExitButtonGUIActionPerformed()
     * @param evt 
     */
    private void ExitButtonGUIActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ExitButtonGUIActionPerformed
        // Close the GUI program by applying System.exit(0);
        JOptionPane.showMessageDialog(null, "Exiting HELPAid GUI Program..");
        System.exit(0);
    }//GEN-LAST:event_ExitButtonGUIActionPerformed
    
    /**
     * The method below is used to add an event display all of the registered Users
     * (Both Organization Representative and Applicant), the User will be directed
     * to the selection panel, whether the User wants to choose registered Representative or Applicant 
     * Method: DisplayUsersBtnActionPerformed()
     * @param evt 
     */
    private void DisplayUsersBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DisplayUsersBtnActionPerformed
        // check if the List of Registered Users is empty according to the ArrayList
        if(HELPAid.getUserList().isEmpty()){
            // It will display the following message if there aren't any registered users
            JOptionPane.showMessageDialog(null, "There aren't any registered Users in the system.");
        } else {
            // If there are any registered Users, it will redirect to the User Selection Panel
            // Set its visibility to true and dispose the previous frame
            UserSelectionPanel userSelWindow = new UserSelectionPanel(HELPAid);
            userSelWindow.setVisible(true);
            dispose();
        }
    }//GEN-LAST:event_DisplayUsersBtnActionPerformed
    
    /**
     * The method below is used to direct the User to the HELP Aid Admin Login Panel
     * Method: HELPAidLoginBtnActionPerformed()
     * @param evt 
     */
    private void HELPAdminLoginBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HELPAdminLoginBtnActionPerformed
        // Display the HELP Aid Admin Login Panel and set its visibility to true
        HELPAidAdminLoginPanel AdminLoginPanel = new HELPAidAdminLoginPanel(HELPAid);
        AdminLoginPanel.setVisible(true);
        // Dispose the previous frame
        dispose();
    }//GEN-LAST:event_HELPAdminLoginBtnActionPerformed
    
    /**
     * The method below is used to add event to redirect the User to the Organization Representative Login Panel
     * Method: HELPOrgRepLoginBtnActionPerformed()
     * @param evt 
     */
    private void HELPOrgRepLoginBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HELPOrgRepLoginBtnActionPerformed
        // Display the Organization Representative Login Panel and set its visibility to true
        RepresentativeLoginPanel RepresentativeLoginPanel = new RepresentativeLoginPanel(HELPAid);
        RepresentativeLoginPanel.setVisible(true);
        // Dispose the previous frame
        dispose();
    }//GEN-LAST:event_HELPOrgRepLoginBtnActionPerformed

    /**
     * This method is used to add event to redirect the User to the Applicant Control Panel
     * Method: EnterApplicantBtnActionPerformed()
     * @param evt
     */
    private void EnterApplicantBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EnterApplicantBtnActionPerformed
        ApplicantEnterController AppEnterControlPanel = new ApplicantEnterController(HELPAid);
        AppEnterControlPanel.setVisible(true);
        dispose();
    }//GEN-LAST:event_EnterApplicantBtnActionPerformed
    
    /**
     * The method below is used to add event to redirect the User to the Donor Login Panel
     * Method: HELPDonorLoginBtnActionPerformed()
     * @param evt 
     */
    private void HELPDonorLoginBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HELPDonorLoginBtnActionPerformed
        // Display the Donor Login Panel and set its visibility to true
        DonorLoginPanel DonorLoginPanel = new DonorLoginPanel(HELPAid);
        DonorLoginPanel.setVisible(true);
        // dispose the previous frame
        dispose();
    }//GEN-LAST:event_HELPDonorLoginBtnActionPerformed
    
    /**
     * main method - start of the program comes from the HELPAidGUI.java
     * The main method is responsible on managing the GUI builder
     * @param args 
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        // Applying try and catch exception generated by Apache NetBeans
        try {
            // Set the preview to Nimbus
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        // catch an exception for ClassNotFoundException
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HELPAidGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        // Catch an exception for InstantinationException
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HELPAidGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        // Catch an exception for IllegalAccessException
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HELPAidGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        // Catch an exception for UnsupportedLookAndFeelException
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HELPAidGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        // Create and display the HELPAidGUI form
        // Applying runnable interface to run the program
        // Implementing lambda expressions to invoke to GUI Program
        java.awt.EventQueue.invokeLater(() -> {
            try {
                // Set its visibility to true to display the form
                new HELPAidGUI().setVisible(true);
            }
            catch(Exception e){
                // printStackTrace method
                e.printStackTrace();
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton DisplayUsersBtn;
    private javax.swing.JButton EnterApplicantBtn;
    private javax.swing.JButton ExitButtonGUI;
    private javax.swing.JButton HELPAdminLoginBtn;
    private javax.swing.JLabel HELPAidLabel;
    private javax.swing.JLabel HELPAidLogo;
    private javax.swing.JLabel HELPAidSystemLabel;
    private javax.swing.JButton HELPDonorLoginBtn;
    private javax.swing.JLabel HELPLOGOLabel;
    private javax.swing.JButton HELPOrgRepLoginBtn;
    private javax.swing.JPanel MainGUIPanelFrame;
    private javax.swing.JPanel SideLeftPanel;
    // End of variables declaration//GEN-END:variables
}